app:
  title: "UDP/TCP Studio (Inspector + Linked X)"
  fps: 60
  hide_timestamp_legend: true
  drop_timestamp_channel: true
  crosshair: true
  crosshair_max_channels: 10


  app:
  title: "UDP/TCP Studio"
  fps: 60

  # Theme options
  theme:
    name: "fusion-light"          # "fusion-light" | "fusion-dark" | "native"
    pg_background: "#0f0f12"      # plot canvas
    pg_foreground: "#e6e6e6"      # axes/labels
    stylesheet: |                 # (optional) QSS additions
      /* Make dock titles a bit cleaner */
      QDockWidget::title { padding: 4px; font-weight: 600; }


data_sources:
  - name: tcp0
    type: tcp_client
    host: "127.0.0.1"
    port: 7000
    format: float32_le_fixed
    length: 22
    timestamp_index: 21
    timestamp_units: s
    timestamp_zero: true

channels:
  - range: "ch0..ch21"

plots:
  - title: "TCP Demo"
    source: tcp0
    channels: ["ch0..ch5", "ch21"] # timestamp will be dropped from plotting if drop_timestamp_channel: true
    window_samples: 5000
    grid: [true, true]
    x_axis: { mode: timestamp, window_s: 6.0, lock_right: true }
    follow_x: true
    x_link_group: g1
    x_link_master: true

  - title: "Another View"
    source: tcp0
    channels: ["ch6..ch10"]
    window_samples: 5000
    grid: [true, true]
    x_axis: { mode: timestamp, window_s: 6.0 }
    follow_x: false # follows the master via x-link
    x_link_group: g1

layout:
  rows:
    - ["TCP Demo"]
    - ["Another View"]
